name: django-vue-store
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.5.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.12.2
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - asgiref==3.8.1
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cryptography==42.0.5
      - defusedxml==0.8.0rc2
      - django==5.0.4
      - django-cors-headers==4.3.1
      - django-rest-framework==0.1.0
      - django-templated-mail==1.1.1
      - djangorestframework==3.15.1
      - djangorestframework-simplejwt==5.3.1
      - djoser==2.2.2
      - idna==3.7
      - oauthlib==3.2.2
      - pillow==10.3.0
      - pycparser==2.22
      - pyjwt==2.8.0
      - python3-openid==3.2.0
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - social-auth-app-django==5.4.0
      - social-auth-core==4.5.3
      - sqlparse==0.5.0
      - stripe==9.2.0
      - typing-extensions==4.11.0
      - urllib3==2.2.1
